kind = "web"
previewPath = "/"
title = "Qamqor"
version = "1.0.0"
id = "artifacts/qamqor"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 18369

[services.development]
run = "pnpm --filter @workspace/qamqor run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/qamqor", "run", "build" ]
publicDir = "artifacts/qamqor/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "18369"
BASE_PATH = "/"
